// <auto-generated />
using System;
using DDDNetCore.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(PortDbContext))]
    [Migration("20260104164922_ExtendDataRequestForUserRights")]
    partial class ExtendDataRequestForUserRights
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DDDNetCore.Domain.DataRequests.DataRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ConsentGivenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestData")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VesselReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VvnReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("ReferenceNumber", "Email");

                    b.ToTable("DataRequests", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.DockAssignments.DockAssignment", b =>
                {
                    b.Property<Guid>("DockAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BerthFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BerthTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("VesselVisitNotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DockAssignmentId");

                    b.HasIndex("VesselVisitNotificationId")
                        .IsUnique();

                    b.HasIndex("DockCode", "BerthFrom");

                    b.ToTable("DockAssignments", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.DockAssignments.DockAssignmentEvent", b =>
                {
                    b.Property<int>("DockAssignmentEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DockAssignmentEventId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DockAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromDockCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DockAssignmentEventId");

                    b.HasIndex("DockAssignmentId");

                    b.ToTable("DockAssignmentEvents", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Docks.Dock", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("DepthM")
                        .HasColumnType("float");

                    b.Property<double>("LengthM")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("MaxDraftM")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Docks");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Docks.DockStorageDistance", b =>
                {
                    b.Property<int>("DockStorageDistanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DockStorageDistanceId"));

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("int");

                    b.Property<string>("DockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StorageAreaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("DockStorageDistanceId");

                    b.HasIndex("DockCode");

                    b.HasIndex("StorageAreaId");

                    b.ToTable("DockStorageDistance");
                });

            modelBuilder.Entity("DDDNetCore.Domain.HumanResources.StaffMember", b =>
                {
                    b.Property<long>("MecanographicNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("ActivityStatus")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndHour")
                        .HasColumnType("time");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartHour")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MecanographicNumber");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("DDDNetCore.Domain.HumanResources.StaffMemberQualification", b =>
                {
                    b.Property<string>("QualificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("StaffMemberMecanographicNumber")
                        .HasColumnType("bigint");

                    b.HasKey("QualificationId");

                    b.HasIndex("StaffMemberMecanographicNumber");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AlternativeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("DDDNetCore.Domain.PrivacyPolicy.PrivacyPolicy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("pt");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PolicyId");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("LanguageCode", "IsActive");

                    b.ToTable("PrivacyPolicies", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.PrivacyPolicy.PrivacyPolicyAcknowledgment", b =>
                {
                    b.Property<Guid>("AcknowledgmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AcknowledgmentId");

                    b.HasIndex("AcknowledgedAt");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PolicyId")
                        .IsUnique();

                    b.ToTable("PrivacyPolicyAcknowledgments", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Resources.PhysicalResource", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("SetupTimeSeconds")
                        .HasColumnType("int");

                    b.HasKey("ResourceId");

                    b.HasIndex("Availability");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PhysicalResources");

                    b.HasDiscriminator<string>("ResourceType").HasValue("PhysicalResource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DDDNetCore.Domain.StorageAreas.StorageArea", b =>
                {
                    b.Property<string>("StorageAreaId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CurrentOccupancyTEU")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxCapacityTEU")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ServesAllDocks")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StorageAreaId");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("StorageAreas");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Users.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivationToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ActivationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Vessels.Vessel", b =>
                {
                    b.Property<string>("ImoNumber")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int?>("CapacityTEU")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VesselTypeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ImoNumber");

                    b.HasIndex("ImoNumber")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerOrganizationId");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Vessels.VesselType", b =>
                {
                    b.Property<string>("VesselTypeId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("CapacityTEU")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("MaxBays")
                        .HasColumnType("int");

                    b.Property<int?>("MaxRows")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTiers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OperationalConstraints")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("VesselTypeId");

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Crew.CrewMember", b =>
                {
                    b.Property<Guid>("CrewMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("VesselVisitNotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VesselVisitNotificationVvnGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CrewMemberId");

                    b.HasIndex("VesselVisitNotificationId");

                    b.HasIndex("VesselVisitNotificationVvnGuid");

                    b.ToTable("CrewMembers", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.DecisionLog", b =>
                {
                    b.Property<Guid>("DecisionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DockAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OfficerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VvnGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DecisionLogId");

                    b.HasIndex("VvnGuid", "AtUtc");

                    b.ToTable("DecisionLogs", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Manifests.CargoManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ManifestType")
                        .HasColumnType("int");

                    b.Property<Guid>("VvnGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VvnGuid", "ManifestType")
                        .IsUnique();

                    b.ToTable("CargoManifests", (string)null);

                    b.HasDiscriminator<int>("ManifestType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Manifests.ManifestEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContainerBayNr")
                        .HasColumnType("int");

                    b.Property<int>("ContainerRowNr")
                        .HasColumnType("int");

                    b.Property<int>("ContainerTierNr")
                        .HasColumnType("int");

                    b.Property<string>("ContainerUniqueId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GoodsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HazardousGoods")
                        .HasColumnType("bit");

                    b.Property<Guid>("ManifestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.HasIndex("ManifestId", "ContainerUniqueId")
                        .IsUnique();

                    b.ToTable("CargoManifestEntries", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.VesselVisitNotification", b =>
                {
                    b.Property<Guid>("VvnGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaptainCitizenId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaptainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaptainNationality")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CrewCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("DockAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Eta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Etd")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoadingCount")
                        .HasColumnType("int");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UnloadingCount")
                        .HasColumnType("int");

                    b.Property<string>("VesselImo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("VesselImoNumber")
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("VisitPurpose")
                        .HasColumnType("int");

                    b.Property<string>("VvnBusinessId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VvnGuid");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RejectedById");

                    b.HasIndex("SubmittedById");

                    b.HasIndex("VesselImoNumber");

                    b.ToTable("VesselVisitNotifications", (string)null);
                });

            modelBuilder.Entity("DockStorageArea", b =>
                {
                    b.Property<string>("DocksCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ServedStorageAreasStorageAreaId")
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("DocksCode", "ServedStorageAreasStorageAreaId");

                    b.HasIndex("ServedStorageAreasStorageAreaId");

                    b.ToTable("DockStorageArea");
                });

            modelBuilder.Entity("DockVesselType", b =>
                {
                    b.Property<string>("AllowedDocksCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AllowedVesselTypesVesselTypeId")
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("AllowedDocksCode", "AllowedVesselTypesVesselTypeId");

                    b.HasIndex("AllowedVesselTypesVesselTypeId");

                    b.ToTable("DockVesselType");
                });

            modelBuilder.Entity("PhysicalResourceStaffMemberQualification", b =>
                {
                    b.Property<string>("PhysicalResourceResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequiredQualificationsQualificationId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PhysicalResourceResourceId", "RequiredQualificationsQualificationId");

                    b.HasIndex("RequiredQualificationsQualificationId");

                    b.ToTable("PhysicalResourceQualifications", (string)null);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Resources.MobileEquipment", b =>
                {
                    b.HasBaseType("DDDNetCore.Domain.Resources.PhysicalResource");

                    b.Property<int?>("AvgContainersPerHour")
                        .HasColumnType("int");

                    b.Property<int?>("ContainersPerTrip")
                        .HasColumnType("int");

                    b.Property<string>("CurrentDockCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaxSpeedKph")
                        .HasColumnType("int");

                    b.Property<string>("MobileEquipmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CurrentDockCode");

                    b.HasDiscriminator().HasValue("MOBILE_EQUIPMENT");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Resources.STSCrane", b =>
                {
                    b.HasBaseType("DDDNetCore.Domain.Resources.PhysicalResource");

                    b.Property<int>("AvgContainersPerHour")
                        .HasColumnType("int");

                    b.Property<string>("InstalledAtDockCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasIndex("InstalledAtDockCode")
                        .IsUnique()
                        .HasFilter("[InstalledAtDockCode] IS NOT NULL");

                    b.ToTable("PhysicalResources", t =>
                        {
                            t.Property("AvgContainersPerHour")
                                .HasColumnName("STSCrane_AvgContainersPerHour");
                        });

                    b.HasDiscriminator().HasValue("STS_CRANE");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Manifests.LoadingCargoManifest", b =>
                {
                    b.HasBaseType("DDDNetCore.Domain.Visits.Manifests.CargoManifest");

                    b.HasIndex("VvnGuid")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Manifests.UnloadingCargoManifest", b =>
                {
                    b.HasBaseType("DDDNetCore.Domain.Visits.Manifests.CargoManifest");

                    b.HasIndex("VvnGuid")
                        .IsUnique();

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("DDDNetCore.Domain.DockAssignments.DockAssignment", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Docks.Dock", "Dock")
                        .WithMany()
                        .HasForeignKey("DockCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DDDNetCore.Domain.Visits.VesselVisitNotification", null)
                        .WithOne("DockAssignment")
                        .HasForeignKey("DDDNetCore.Domain.DockAssignments.DockAssignment", "VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dock");
                });

            modelBuilder.Entity("DDDNetCore.Domain.DockAssignments.DockAssignmentEvent", b =>
                {
                    b.HasOne("DDDNetCore.Domain.DockAssignments.DockAssignment", null)
                        .WithMany("AssignmentHistory")
                        .HasForeignKey("DockAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Docks.DockStorageDistance", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Docks.Dock", "Dock")
                        .WithMany()
                        .HasForeignKey("DockCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDNetCore.Domain.StorageAreas.StorageArea", "StorageArea")
                        .WithMany()
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dock");

                    b.Navigation("StorageArea");
                });

            modelBuilder.Entity("DDDNetCore.Domain.HumanResources.StaffMemberQualification", b =>
                {
                    b.HasOne("DDDNetCore.Domain.HumanResources.StaffMember", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("StaffMemberMecanographicNumber");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Organizations.Organization", b =>
                {
                    b.OwnsMany("DDDNetCore.Domain.Organizations.Representative", "Representatives", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CitizenId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)");

                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<Guid>("RepresentativeId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("Email");

                            b1.HasIndex("OrganizationId");

                            b1.ToTable("Representative");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Representatives");
                });

            modelBuilder.Entity("DDDNetCore.Domain.PrivacyPolicy.PrivacyPolicyAcknowledgment", b =>
                {
                    b.HasOne("DDDNetCore.Domain.PrivacyPolicy.PrivacyPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("DDDNetCore.Domain.StorageAreas.StorageArea", b =>
                {
                    b.OwnsOne("DDDNetCore.Domain.StorageAreas.WarehouseSpec", "WarehouseSpec", b1 =>
                        {
                            b1.Property<string>("StorageAreaId")
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<int>("WarehouseSpecId")
                                .HasColumnType("int");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.OwnsOne("DDDNetCore.Domain.StorageAreas.YardSpec", "YardSpec", b1 =>
                        {
                            b1.Property<string>("StorageAreaId")
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<int>("YardSpecId")
                                .HasColumnType("int");

                            b1.HasKey("StorageAreaId");

                            b1.ToTable("StorageAreas");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");
                        });

                    b.Navigation("WarehouseSpec");

                    b.Navigation("YardSpec");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Users.User", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasPrincipalKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Vessels.Vessel", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Organizations.Organization", "OwnerOrganization")
                        .WithMany()
                        .HasForeignKey("OwnerOrganizationId")
                        .HasPrincipalKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DDDNetCore.Domain.Vessels.VesselType", "VesselType")
                        .WithMany("Vessels")
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerOrganization");

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Crew.CrewMember", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Visits.VesselVisitNotification", null)
                        .WithMany()
                        .HasForeignKey("VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDNetCore.Domain.Visits.VesselVisitNotification", null)
                        .WithMany("CrewMembers")
                        .HasForeignKey("VesselVisitNotificationVvnGuid");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Manifests.ManifestEntry", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Visits.Manifests.CargoManifest", null)
                        .WithMany("Entries")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.VesselVisitNotification", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Users.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("DDDNetCore.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .HasPrincipalKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DDDNetCore.Domain.Users.User", "RejectedBy")
                        .WithMany()
                        .HasForeignKey("RejectedById");

                    b.HasOne("DDDNetCore.Domain.Users.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById");

                    b.HasOne("DDDNetCore.Domain.Vessels.Vessel", "Vessel")
                        .WithMany("VesselVisitNotifications")
                        .HasForeignKey("VesselImoNumber");

                    b.Navigation("ApprovedBy");

                    b.Navigation("Organization");

                    b.Navigation("RejectedBy");

                    b.Navigation("SubmittedBy");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("DockStorageArea", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Docks.Dock", null)
                        .WithMany()
                        .HasForeignKey("DocksCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDNetCore.Domain.StorageAreas.StorageArea", null)
                        .WithMany()
                        .HasForeignKey("ServedStorageAreasStorageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DockVesselType", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Docks.Dock", null)
                        .WithMany()
                        .HasForeignKey("AllowedDocksCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDNetCore.Domain.Vessels.VesselType", null)
                        .WithMany()
                        .HasForeignKey("AllowedVesselTypesVesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhysicalResourceStaffMemberQualification", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Resources.PhysicalResource", null)
                        .WithMany()
                        .HasForeignKey("PhysicalResourceResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDNetCore.Domain.HumanResources.StaffMemberQualification", null)
                        .WithMany()
                        .HasForeignKey("RequiredQualificationsQualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DDDNetCore.Domain.Resources.MobileEquipment", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Docks.Dock", "CurrentAllocation")
                        .WithMany("MobileEquipments")
                        .HasForeignKey("CurrentDockCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentAllocation");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Resources.STSCrane", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Docks.Dock", "InstalledAt")
                        .WithOne("StsCrane")
                        .HasForeignKey("DDDNetCore.Domain.Resources.STSCrane", "InstalledAtDockCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InstalledAt");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Manifests.LoadingCargoManifest", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Visits.VesselVisitNotification", null)
                        .WithOne("LoadingManifest")
                        .HasForeignKey("DDDNetCore.Domain.Visits.Manifests.LoadingCargoManifest", "VvnGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Manifests.UnloadingCargoManifest", b =>
                {
                    b.HasOne("DDDNetCore.Domain.Visits.VesselVisitNotification", null)
                        .WithOne("UnloadingManifest")
                        .HasForeignKey("DDDNetCore.Domain.Visits.Manifests.UnloadingCargoManifest", "VvnGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DDDNetCore.Domain.DockAssignments.DockAssignment", b =>
                {
                    b.Navigation("AssignmentHistory");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Docks.Dock", b =>
                {
                    b.Navigation("MobileEquipments");

                    b.Navigation("StsCrane");
                });

            modelBuilder.Entity("DDDNetCore.Domain.HumanResources.StaffMember", b =>
                {
                    b.Navigation("Qualifications");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Vessels.Vessel", b =>
                {
                    b.Navigation("VesselVisitNotifications");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Vessels.VesselType", b =>
                {
                    b.Navigation("Vessels");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.Manifests.CargoManifest", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DDDNetCore.Domain.Visits.VesselVisitNotification", b =>
                {
                    b.Navigation("CrewMembers");

                    b.Navigation("DockAssignment");

                    b.Navigation("LoadingManifest");

                    b.Navigation("UnloadingManifest");
                });
#pragma warning restore 612, 618
        }
    }
}
